### ISSUE TITLE
[doc] 이슈 및 PR 템플릿 제작

### ISSUE THREAD

**Issue by ChangDaeJun** [ChangDaeJun/PFI#6]
### 개요
이슈 및 PR 작성 시 필요한 양식을 제작하고, 작성 시 자동으로 제공하도록 설정한다.

### Todo
- [ ] 이슈 양식 만들기
- [ ] PR 양식 만들기
- [ ] 이슈 양식 설정하기
- [ ] PR 양식 설정하기

### Assignees
* ChangDaeJun

**Comment by ChangDaeJun** [comment]
인사이트 > Community Standards > 초기 설정 가능
