### ISSUE TITLE
[doc] 위키 사용을 위한 사전조사

### ISSUE THREAD

**Issue by ChangDaeJun** [ChangDaeJun/PFI#7]
### 개요
프로젝트 위키를 사용하기 위한 툴과 사용법을 조사하고, 실제 위키를 작성한다. 기본적으로 깃허브 위키는 작성하되 다른 툴을 사용할 경우엔 이전한다.

### Todo
- [ ] 위키 작성을 위한 여러 방안 탐색
- [ ] 위키에 작성할 목록 제작
- [ ] 깃허브 위키에 작성

### Assignees
* ChangDaeJun
* DAEHOCHANG
