### ISSUE TITLE
[doc] 베타서버 구축을 위한 조사

### ISSUE THREAD

**Issue by ChangDaeJun** [ChangDaeJun/PFI#8]
### 개요
프로젝트 베타서버 구축을 위한 방안과 실행 계획에 대해 작성한다.

### Todo
- [ ] 베타서버 구축에 대한 자료조사(Wiki 작성)
- [ ] 베타서버 구축에 대한 방안 마련
- [ ] 베타서버 구축에 대한 계획 마련

### Assginees
* ChangDaeJun
* DAEHOCHANG
